-- MySQL Script generated by MySQL Workbench
-- Sun Jun 14 21:57:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_organization
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_organization
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_organization` DEFAULT CHARACTER SET utf8 ;
USE `db_organization` ;

-- -----------------------------------------------------
-- Table `db_organization`.`specialization`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organization`.`specialization` (
  `idspecialization` INT NOT NULL AUTO_INCREMENT,
  `specialization_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idspecialization`),
  UNIQUE INDEX `idspecialization_UNIQUE` (`idspecialization` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_organization`.`property`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organization`.`property` (
  `idproperty` INT NOT NULL AUTO_INCREMENT,
  `property_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idproperty`),
  UNIQUE INDEX `idproperty_UNIQUE` (`idproperty` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_organization`.`organizations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organization`.`organizations` (
  `idorganizations` INT NOT NULL AUTO_INCREMENT,
  `organizations_name` VARCHAR(45) NOT NULL,
  `organizations_adress` VARCHAR(45) NOT NULL,
  `organizations_email` VARCHAR(45) NOT NULL,
  `organizations_site_adress` VARCHAR(45) NOT NULL,
  `organizations_work_start_time` DATETIME NOT NULL,
  `organizations_work_end_time` DATETIME NOT NULL,
  `organizations_description` VARCHAR(45) NOT NULL,
  `specialization_idspecialization` INT NOT NULL,
  `property_idproperty` INT NOT NULL,
  PRIMARY KEY (`idorganizations`),
  UNIQUE INDEX `idorganizations_UNIQUE` (`idorganizations` ASC) VISIBLE,
  INDEX `fk_organizations_specialization1_idx` (`specialization_idspecialization` ASC) VISIBLE,
  INDEX `fk_organizations_property1_idx` (`property_idproperty` ASC) VISIBLE,
  CONSTRAINT `fk_organizations_specialization1`
    FOREIGN KEY (`specialization_idspecialization`)
    REFERENCES `db_organization`.`specialization` (`idspecialization`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_organizations_property1`
    FOREIGN KEY (`property_idproperty`)
    REFERENCES `db_organization`.`property` (`idproperty`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_organization`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organization`.`category` (
  `idcategory` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategory`),
  UNIQUE INDEX `idcategory_UNIQUE` (`idcategory` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_organization`.`phone_numbers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_organization`.`phone_numbers` (
  `idphone_numbers` INT NOT NULL AUTO_INCREMENT,
  `phone_numbers_number` VARCHAR(45) NOT NULL,
  `phone_numbers_fax` TINYINT(1) NOT NULL,
  `category_idcategory` INT NOT NULL,
  `organizations_idorganizations` INT NOT NULL,
  PRIMARY KEY (`idphone_numbers`),
  UNIQUE INDEX `idphone_numbers_UNIQUE` (`idphone_numbers` ASC) VISIBLE,
  INDEX `fk_phone_numbers_category_idx` (`category_idcategory` ASC) VISIBLE,
  INDEX `fk_phone_numbers_organizations1_idx` (`organizations_idorganizations` ASC) VISIBLE,
  CONSTRAINT `fk_phone_numbers_category`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `db_organization`.`category` (`idcategory`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_phone_numbers_organizations1`
    FOREIGN KEY (`organizations_idorganizations`)
    REFERENCES `db_organization`.`organizations` (`idorganizations`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
